Enhancement/locks
openbill-service/openbill-core pull request #19
Opened 2021-09-14 10:47 UTC by vivanov-bitzlato

account blocking mechanism

2021-09-14 14:43 UTC, dapi commented on sql/4_trigger_openbill_locks_insert.sql
> +  END IF;
может на constraint перенесем?

2021-09-14 15:40 UTC, radanisk requested changes

2021-09-14 15:40 UTC, radanisk commented on sql/07_migration_locks.sql
> +  username        character varying(255) not null,
username не хотим проставлять автоматически, как это сделано для транзакций https://github.com/openbill-service/openbill-core/blob/master/sql/1_trigger_add_user_to_transaction.sql ?

2021-09-15 08:33 UTC, vivanov-bitzlato commented on sql/07_migration_locks.sql
> +  meta            hstore not null default ''::hstore,
ок

2021-09-15 08:53 UTC, vivanov-bitzlato commented on sql/07_migration_locks.sql
> +  username        character varying(255) not null,
ok

2021-09-15 09:28 UTC, vivanov-bitzlato commented on sql/4_trigger_openbill_locks_insert.sql
> +  UPDATE OPENBILL_ACCOUNTS SET amount_cents = amount_cents - NEW.amount_cents, locked_cents = locked_cents + NEW.amount_cents WHERE id = NEW.account_id;
Вижу аналогичный триггер для транзакций, который работает точно также, как у меня: https://github.com/openbill-service/openbill-core/blob/master/sql/1_trigger_add_user_to_transaction.sql
Очень-очень не хочется связываться с блокировками, это не решение проблемы, а только ее усложнение.
Рекомендую использовать при вызове операций режим изоляции транзакций SERIALIZABLE
https://vladmihalcea.com/postgresql-triggers-isolation-levels/

2021-09-15 15:19 UTC, vivanov-bitzlato commented on sql/4_trigger_openbill_locks_insert.sql
> +  END IF;
там есть fk. Идея проверки в том, что поле lock_key заполняется только в том случае, если нам надо разблокировать средства

2021-09-17 07:50 UTC, radanisk commented on sql/4_trigger_openbill_locks_insert.sql
> +  UPDATE OPENBILL_ACCOUNTS SET amount_cents = amount_cents - NEW.amount_cents, locked_cents = locked_cents + NEW.amount_cents WHERE id = NEW.account_id;
Из репы не понятно, какой уровень изоляции транзакций используется по умолчанию.
@dapi может ты подскажешь?
Или, как вариант, для функции может явно укажем уровень изоляции? Это же возможно?

2021-09-20 10:37 UTC, dapi commented on sql/4_trigger_openbill_locks_insert.sql
> +  END IF;
`CHECK ((amount_cents < 0 AND lock_key is NOT NULL) or (amount_cents >0 AND lock_key is NULL))`
?

2021-09-20 13:36 UTC, vivanov-bitzlato commented on sql/4_trigger_openbill_locks_insert.sql
> +  END IF;
сделал

2021-09-20 16:26 UTC, closed without merging